model_names <- list(
  client_model = c("Agency Creating Profile",
  "Bed and Unit Inventory",
  "Chronic Homeless Pit",
  "Client Addresses",
  "Client Alerts",
  "Client Assessment Custom",
  "Client Assessments",
  "Client Care Team Members",
  "Client Contacts",
  "Client Custom",
  "Client Field Interactions",
  "Client Interactions",
  "Client Notes - Client Level",
  "Client Notes - Enrollment Level",
  "Client Referral Status",
  "Clients",
  "Coordinated Entry Event",
  "Current Living Situation",
  "Current Living Situation Custom",
  "Enrolling Agency",
  "Enrollments",
  "Entry Custom",
  "Entry Screen",
  "Followup Custom",
  "Followup Screen",
  "Goals",
  "Program Custom",
  "Program Funding Sources",
  "Program Sites",
  "Programs",
  "Referral Connections Enrollment",
  "Referral History",
  "Referral Notes",
  "Referrals",
  "Referto Programs",
  "Release of Information",
  "Service Attendance Dates",
  "Service Expenses",
  "Service Funding",
  "Service Time Tracking",
  "Services",
  "Status Update Custom",
  "Status Update Screen",
  "Update/Exit Custom",
  "Update/Exit Screen") |> {\(x) {setNames(x, nm = x)}}()
)
